---
- name: Mention the playbook name
  hosts: localhost ##server names
  become: yes
  tasks: 
  - name: Installing Nginx server
    yum:
      name: nginx
      state: installed
  - name: Checking server status
    service:
      name: nginx
      state: started