- name: Setting up the catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Running The script or Downkonading the setup
    shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
 
  - name: Install Nodejs from the script
    yum:
      name: nodejs 
      state: installed

  - name: Check roboshop user is available or not  
    command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc != 0
    name: Create user named Roboshop    
    user:
      name: roboshop
  
  - name: Check the directory exist or not
    stat:
      path: /app
    register: directory
  - name: Print the output of directory 
    debug:
      msg: "output is {{directory}}"
    