- name: Setting Up MongoDB Server
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: Installing mongodb server
    yum:
      name: mongodb-org
      state: installed
  - name: Checking the status of server
    service:
      name: mongod
      state: started
      enabled: yes
  - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
    replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'