- name: Installing the user component
  hosts: user
  become: yes
  tasks:
  - name: Setting up the nodejs repos with shell command
    shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: Installing node js 
    yum:
      name: nodejs
      state: installed

  - name: check the user is available or not
    command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc !=0 
    name: create the roboshopuser
    user: 
      name: roboshop

  - name: directory is present or not
    stat:
      path: /app
    register: directory
  
  - name: print the status or directory presence
    debug:
      msg: directory

  # - when: driectory.stat == false
  #   name: create a directory /app in the user component
  #   file:
  #     path: /app
  #     state: directory
    